### ISSUE TITLE
Restore hipchat token from previous session

### ISSUE THREAD

**Issue by fbiehl** [my8bit/timer.tomatoes.work#11]
Scenario:

1 - setup auth token in application & verify it is working
2 - close application
3 - reopen application

Expected: starting timer changes hipchat status to busy
Actual: no status change on hipchat + in configuration no token is restored

Note: chrome inspector for application local storage shows info is present

**Comment by my8bit** [comment]
@fbiehl Fixed and closed.

**Comment by fbiehl** [comment]
@my8bit thanks!! :)
